using Content.Client.UserInterface.Controls;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Utility;

namespace Content.Client._Stories.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class SponsorPerksWindow : FancyWindow
{
    public SponsorPerksWindow()
    {
        RobustXamlLoader.Load(this);

        var cfg = IoCManager.Resolve<IConfigurationManager>();
        var uriOpener = IoCManager.Resolve<IUriOpener>();

        PerksText.SetMessage(FormattedMessage.FromMarkupPermissive(Loc.GetString("stories-sponsor-perks-description")));

        BoostyLinkButton.OnPressed += _ => uriOpener.OpenUri(cfg.GetCVar(CCVars.InfoLinksPatreon));
    }
}
