using System;
using System.Collections.Generic;
using System.Linq;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._Stories.TTS;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Random;

namespace Content.Client._Stories.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class TTSVoiceSelectionWindow : FancyWindow
{
    public Action<string>? OnVoiceSelected;
    public Action<string>? OnPreviewPlay;

    private readonly List<(TTSVoicePrototype Voice, bool Unlocked)> _allVoices;
    private string? _currentVoice;
    private readonly IRobustRandom _random;

    private readonly List<(Button Btn, TTSVoicePrototype Voice, bool Unlocked, string Category)> _voiceButtons = new();
    private readonly Dictionary<string, BoxContainer> _categoryContents = new();
    private readonly Dictionary<string, Button> _categoryTabButtons = new();
    private string _activeCategory = "All";
    private BoxContainer _allContent = new();

    public TTSVoiceSelectionWindow(List<(TTSVoicePrototype Voice, bool Unlocked)> voices, string? currentVoice)
    {
        RobustXamlLoader.Load(this);
        _random = IoCManager.Resolve<IRobustRandom>();
        _allVoices = voices;
        _currentVoice = currentVoice;

        BuildTabs();

        SearchBar.OnTextChanged += OnSearchChanged;

        RandomButton.OnPressed += _ => SelectRandomVoice();
        PreviewButton.OnPressed += _ =>
        {
            if (_currentVoice != null)
                OnPreviewPlay?.Invoke(_currentVoice);
        };
    }

    private void BuildTabs()
    {
        TabsHeader.DisposeAllChildren();
        TabsContent.DisposeAllChildren();
        _voiceButtons.Clear();
        _categoryContents.Clear();
        _categoryTabButtons.Clear();

        var grouped = _allVoices.GroupBy(v => string.IsNullOrWhiteSpace(v.Voice.Category) ? "Uncategorized" : v.Voice.Category);

        AddCategoryTab("All", Loc.GetString("stories-tts-category-all"));

        foreach (var group in grouped.OrderBy(g => g.Key))
        {
            var tabName = Loc.GetString(group.Key);
            if (tabName == group.Key && !group.Key.StartsWith("stories-tts-category-"))
            {
                tabName = group.Key;
            }
            AddCategoryTab(group.Key, tabName);
        }

        foreach (var (voice, unlocked) in _allVoices)
        {
            var category = string.IsNullOrWhiteSpace(voice.Category) ? "Uncategorized" : voice.Category;

            var btnCat = CreateVoiceButton(voice, unlocked);
            _categoryContents[category].AddChild(btnCat);
            _voiceButtons.Add((btnCat, voice, unlocked, category));

            var btnAll = CreateVoiceButton(voice, unlocked);
            _allContent.AddChild(btnAll);
            _voiceButtons.Add((btnAll, voice, unlocked, "All"));
        }

        SetActiveTab("All");
    }

    private void AddCategoryTab(string id, string title)
    {
        var btn = new Button { Text = title };
        btn.OnPressed += _ => SetActiveTab(id);
        TabsHeader.AddChild(btn);
        _categoryTabButtons[id] = btn;

        var content = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, Margin = new Thickness(5) };
        content.Visible = false;

        if (id == "All")
            _allContent = content;
        else
            _categoryContents[id] = content;

        TabsContent.AddChild(content);
    }

    private Button CreateVoiceButton(TTSVoicePrototype voice, bool unlocked)
    {
        var btn = new Button
        {
            Text = unlocked ? Loc.GetString(voice.Name) : $"🔒 {Loc.GetString(voice.Name)}",
            HorizontalAlignment = Control.HAlignment.Stretch,
            Margin = new Thickness(0, 0, 0, 2),
            Disabled = !unlocked,
            ToolTip = unlocked ? string.Empty : Loc.GetString("stories-tts-sponsor-locked-tooltip")
        };

        if (voice.ID == _currentVoice)
            btn.StyleClasses.Add("ButtonColorGreen");

        btn.OnPressed += _ =>
        {
            _currentVoice = voice.ID;
            OnVoiceSelected?.Invoke(voice.ID);
            UpdateSelectionHighlight();
        };

        return btn;
    }

    private void SetActiveTab(string category)
    {
        _activeCategory = category;

        _allContent.Visible = false;
        foreach (var content in _categoryContents.Values)
            content.Visible = false;

        foreach (var (cat, btn) in _categoryTabButtons)
        {
            if (cat == category)
            {
                if (!btn.StyleClasses.Contains("ButtonColorGreen"))
                    btn.StyleClasses.Add("ButtonColorGreen");
            }
            else
            {
                btn.StyleClasses.Remove("ButtonColorGreen");
            }
        }

        if (category == "All")
            _allContent.Visible = true;
        else if (_categoryContents.TryGetValue(category, out var contentBox))
            contentBox.Visible = true;
    }

    private void UpdateSelectionHighlight()
    {
        foreach (var (btn, voice, _, _) in _voiceButtons)
        {
            if (voice.ID == _currentVoice)
            {
                if (!btn.StyleClasses.Contains("ButtonColorGreen"))
                    btn.StyleClasses.Add("ButtonColorGreen");
            }
            else
            {
                btn.StyleClasses.Remove("ButtonColorGreen");
            }
        }
    }

    private void OnSearchChanged(LineEdit.LineEditEventArgs args)
    {
        var query = args.Text.Trim().ToLowerInvariant();

        bool currentCategoryHasMatch = false;

        foreach (var (cat, tabBtn) in _categoryTabButtons)
        {
            if (cat == "All")
            {
                tabBtn.Visible = true;
                continue;
            }

            bool hasMatch = false;
            foreach (var (_, voice, _, tab) in _voiceButtons)
            {
                if (tab == cat)
                {
                    var voiceName = Loc.GetString(voice.Name).ToLowerInvariant();
                    if (string.IsNullOrEmpty(query) || voiceName.Contains(query))
                    {
                        hasMatch = true;
                        break;
                    }
                }
            }

            tabBtn.Visible = hasMatch;
            if (cat == _activeCategory && hasMatch)
                currentCategoryHasMatch = true;
        }

        if (!string.IsNullOrEmpty(query) && _activeCategory != "All" && !currentCategoryHasMatch)
        {
            SetActiveTab("All");
        }

        foreach (var (btn, voice, _, tab) in _voiceButtons)
        {
            if (tab != _activeCategory) continue;

            var voiceName = Loc.GetString(voice.Name).ToLowerInvariant();
            btn.Visible = string.IsNullOrEmpty(query) || voiceName.Contains(query);
        }
    }

    private void SelectRandomVoice()
    {
        var unlockedVoices = _allVoices.Where(v => v.Unlocked).Select(v => v.Voice).ToList();
        if (unlockedVoices.Count == 0) return;

        var randomVoice = _random.Pick(unlockedVoices);
        _currentVoice = randomVoice.ID;
        OnVoiceSelected?.Invoke(randomVoice.ID);

        var targetCategory = randomVoice.SponsorOnly ? "Sponsor" : (string.IsNullOrWhiteSpace(randomVoice.Category) ? "Uncategorized" : randomVoice.Category);
        SetActiveTab(targetCategory);

        SearchBar.Text = "";
        OnSearchChanged(new LineEdit.LineEditEventArgs(SearchBar, ""));

        UpdateSelectionHighlight();
    }
}
