using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Stories.Chat;

[GenerateTypedNameReferences]
public sealed partial class ChatFilterWindow : FancyWindow
{
    private readonly ChatFilterSystem _filterSystem;

    public ChatFilterWindow()
    {
        RobustXamlLoader.Load(this);
        _filterSystem = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<ChatFilterSystem>();

        var (bWords, rWords) = _filterSystem.GetCurrentConfigStrings();

        BanwordsEdit.TextRope = new Rope.Leaf(bWords);
        BanwordsEdit.Placeholder = new Rope.Leaf(Loc.GetString("stories-chat-filter-banwords-placeholder"));

        ReplacementsEdit.TextRope = new Rope.Leaf(rWords);
        ReplacementsEdit.Placeholder = new Rope.Leaf(Loc.GetString("stories-chat-filter-replacements-placeholder"));

        ToggleBanwordsButton.OnPressed += _ =>
        {
            BanwordsContainer.Visible = !BanwordsContainer.Visible;
            ToggleBanwordsButton.Text = Loc.GetString(BanwordsContainer.Visible
                ? "stories-chat-filter-banwords-toggle-hide"
                : "stories-chat-filter-banwords-toggle-show");
        };

        SaveButton.OnPressed += _ =>
        {
            _filterSystem.SaveConfig(
                Rope.Collapse(BanwordsEdit.TextRope),
                Rope.Collapse(ReplacementsEdit.TextRope)
            );
            Close();
        };
    }
}
