using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stories.Sponsors.XenoSkins;

[GenerateTypedNameReferences]
public sealed partial class XenoSkinsWindow : FancyWindow
{
    public XenoSkinsWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
