using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._RMC14.Xenonids.Evolution;

[GenerateTypedNameReferences]
public sealed partial class XenoEvolutionWindow : DefaultWindow
{
    // Stories-EvoQueue
    public Func<TimeSpan?>? GetOfferRemaining;

    public XenoEvolutionWindow()
    {
        RobustXamlLoader.Load(this);
    }

    // Stories-EvoQueue
    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (GetOfferRemaining?.Invoke() is { } remaining && remaining > TimeSpan.Zero)
        {
            QueueTimerLabel.Visible = true;
            QueueTimerLabel.Text = Loc.GetString("stories-xeno-ui-queue-timer", ("seconds", (int) Math.Ceiling(remaining.TotalSeconds)));
        }
        else
        {
            QueueTimerLabel.Visible = false;
        }
    }
}
