using System;
using System.Collections.Generic;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Timing;
using Robust.Shared.Prototypes;

namespace Content.Client._Stories.Ordnance.Simulator;

[GenerateTypedNameReferences]
public sealed partial class DemolitionsSimulatorWindow : DefaultWindow
{
    [Dependency] private readonly IGameTiming _timing = default!;

    public Action? OnDetonate;

    private TimeSpan _nextDetonation;
    private string _currentCategory = "Xeno";
    private List<EntProtoId> _currentProtos = new();
    private bool _hasItem;

    private bool _isConfirmingDetonate = false;
    private TimeSpan _confirmTimeout;

    public DemolitionsSimulatorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Viewport.ViewportSize = new Vector2i(1200, 1200);
        Viewport.Eye = new FixedEye();

        DetonateButton.OnPressed += _ =>
        {
            if (!_hasItem) return;

            if (!_isConfirmingDetonate)
            {
                _isConfirmingDetonate = true;
                _confirmTimeout = _timing.CurTime + TimeSpan.FromSeconds(3);
                DetonateButton.Text = Loc.GetString("stories-demo-sim-confirm");
                return;
            }

            _isConfirmingDetonate = false;
            DetonateButton.Text = Loc.GetString("stories-demo-sim-detonate");
            OnDetonate?.Invoke();
        };
    }

    public void UpdateState(bool hasItem, string? itemName, TimeSpan nextDetonationTime, TimeSpan cooldown, string selectedCategory, EntProtoId selectedPrototype, Dictionary<string, List<EntProtoId>> categories)
    {
        _hasItem = hasItem;
        ItemLabel.Text = hasItem ? itemName : Loc.GetString("stories-demo-sim-none");
        EjectButton.Disabled = !hasItem;

        _nextDetonation = nextDetonationTime;

        ModeXenoButton.Pressed = selectedCategory == "Xeno";
        ModeStructureButton.Pressed = selectedCategory == "Structure";

        if (_currentCategory != selectedCategory || _currentProtos.Count == 0)
        {
            _currentCategory = selectedCategory;
            UpdateDropdownList(categories);
        }

        SelectDropdownItem(selectedPrototype);
    }

    private void UpdateDropdownList(Dictionary<string, List<EntProtoId>> categories)
    {
        PrototypeDropdown.Clear();

        if (categories.TryGetValue(_currentCategory, out var protos))
        {
            _currentProtos = protos;
        }
        else
        {
            _currentProtos.Clear();
        }

        for (int i = 0; i < _currentProtos.Count; i++)
        {
            PrototypeDropdown.AddItem(Loc.GetString($"stories-demo-sim-proto-{_currentProtos[i].Id}"), i);
        }

        if (_currentProtos.Count > 0)
        {
            PrototypeDropdown.SelectId(0);
        }
    }

    private void SelectDropdownItem(EntProtoId prototype)
    {
        for (int i = 0; i < _currentProtos.Count; i++)
        {
            if (_currentProtos[i] == prototype)
            {
                PrototypeDropdown.SelectId(i);
                break;
            }
        }
    }

    public string? GetPrototypeByIndex(int index)
    {
        if (index >= 0 && index < _currentProtos.Count)
            return _currentProtos[index].Id;
        return null;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var remaining = _nextDetonation - _timing.CurTime;

        if (_isConfirmingDetonate && _timing.CurTime > _confirmTimeout)
        {
            _isConfirmingDetonate = false;
            DetonateButton.Text = Loc.GetString("stories-demo-sim-detonate");
        }

        if (remaining.TotalSeconds > 0)
        {
            CooldownLabel.Text = Loc.GetString("stories-demo-sim-cooldown-time", ("time", (int)remaining.TotalSeconds));
            DetonateButton.Disabled = true;
            _isConfirmingDetonate = false;
            DetonateButton.Text = Loc.GetString("stories-demo-sim-detonate");
        }
        else
        {
            CooldownLabel.Text = Loc.GetString("stories-demo-sim-ready");
            DetonateButton.Disabled = !_hasItem;
        }
    }
}
