- type: rank
  id: RMCRankTSEMarine
  name: Морпех
  prefix: Мрпх.
  paygrade: E1

- type: rank
  id: RMCRankTSELanceCorporal
  name: Младший Капрал
  prefix: МКпрл.
  paygrade: E2

- type: rank
  id: RMCRankTSECorporal
  name: Капрал
  prefix: Кпрл.
  paygrade: E3

- type: rank
  id: RMCRankTSESergeant
  name: Сержант
  prefix: Серж.
  paygrade: E4

- type: rank
  id: RMCRankTSEColourSergeant
  name: Старший Сержант
  prefix: ССерж.
  paygrade: E5

- type: rank
  id: RMCRankTSEWarrantOfficer1
  name: Уоррент Офицер Класс 1
  prefix: УО1.
  paygrade: E6

- type: rank
  id: RMCRankTSEWarrantOfficer2
  name: Уоррент Офицер Класс 2
  prefix: УО2.
  paygrade: E7

- type: rank
  id: RMCRankTSESecondLieutenant
  name: Второй Лейтенант
  prefix: 2ой ЛТ
  paygrade: O1

- type: rank
  id: RMCRankTSELieutenant
  name: Лейтенант
  prefix: Лт.
  paygrade: O2

- type: rank
  id: RMCRankTSECaptain
  name: Капитан
  prefix: Капитан
  paygrade: O3

- type: rank
  id: RMCRankTSEMajor
  name: Майор
  prefix: Майор
  paygrade: O4

- type: rank
  id: RMCRankTSELieutenantColonel
  name: Лейтенант Полковник
  prefix: Лт.Полк.
  paygrade: O5

- type: rank
  id: RMCRankTSEColonel
  name: Полковник
  prefix: Полк.
  paygrade: O6

- type: rank
  id: RMCRankTSEBrigadier
  name: Бригадный Генерал
  prefix: Бриг.
  paygrade: O7

- type: rank
  id: RMCRankTSEMajorGeneral
  name: Генерал Майор
  prefix: Майор Ген.
  paygrade: O8

- type: rank
  id: RMCRankTSELieutenantGeneral
  name: Лейтенант Генерал
  prefix: Лт Ген.
  paygrade: O9

- type: rank
  id: RMCRankTSEGeneral
  name: Генерал
  prefix: Ген.
  paygrade: O10
  
- type: rank
  id: RMCRankTSEEmpress
  name: Императрица
  prefix: ЕВ.

# The below ranks are for the Para insert on Hybrisa

- type: rank
  id: RMCRankParaPrivate
  name: Рядовой
  prefix: Ряд.
  paygrade: E1

- type: rank
  id: RMCRankParaPrivateSecondClass
  name: Рядовой 2-го Класса
  prefix: Ряд.2.
  paygrade: E2

- type: rank
  id: RMCRankParaLanceCorporal
  name: Младший Капрал
  prefix: Мл.Капрал
  paygrade: E3

- type: rank
  id: RMCRankParaCorporal
  name: Капрал
  prefix: Капрал
  paygrade: E4

- type: rank
  id: RMCRankParaSergeant
  name: Сержант
  prefix: Серж.
  paygrade: E5

- type: rank
  id: RMCRankParaStaffSergeant
  name: Штаб-Сержант
  prefix: Штаб-Серж.
  paygrade: E6

- type: rank
  id: RMCRankParaWarrantOfficerClass2
  name: Уоррент Офицер Класс 2
  prefix: УО2.
  paygrade: E7

- type: rank
  id: RMCRankParaSecondLieutenant
  name: Второй Лейтенант
  prefix: 2-й Лт.
  paygrade: O1

- type: rank
  id: RMCRankParaLieutenant
  name: Лейтенант
  prefix: Лт.
  paygrade: O2

- type: rank
  id: RMCRankParaCaptain
  name: Капитан
  prefix: Капитан
  paygrade: O3

- type: rank
  id: RMCRankParaMajor
  name: Майор
  prefix: Майор
  paygrade: O4

- type: rank
  id: RMCRankParaLieutenantColonel
  name: Подполковник
  prefix: Подполк.
  paygrade: O5

- type: rank
  id: RMCRankParaColonel
  name: Полковник
  prefix: Полк.
  paygrade: O6

- type: rank
  id: RMCRankParaBrigadier
  name: Бригадир
  prefix: Бриг.
  paygrade: O7

- type: rank
  id: RMCRankParaMajorGeneral
  name: Генерал-Майор
  prefix: Ген.-Майор
  paygrade: O8

- type: rank
  id: RMCRankParaGeneralBrigade
  name: Бригадный Генерал
  prefix: Бриг.Ген.
  paygrade: O9
