# МеталСидж
- type: rank
  id: RMCRankProvostSectorMarshal
  name: Секторальный Маршал
  prefix: Сек. Маршал
  paygrade: O9

# Admin
- type: rank
  id: RMCRankProvostSeniorMarshal
  name: Старший Маршал
  prefix: Ст. Маршал
  paygrade: O8

# Admin
- type: rank
  id: RMCRankProvostMarshal
  name: Маршал
  prefix: Маршал
  paygrade: O7

# Admin
- type: rank
  id: RMCRankProvostDeputyMarshal
  name: Заместитель Маршала
  prefix: Зам. Маршала
  paygrade: O6

- type: rank
  id: RMCRankProvostChiefInspector
  name: Главный Инспектор
  prefix: Глав. Инсп.
  paygrade: O5

- type: rank
  id: RMCRankProvostInspector
  name: Инспектор военной полиции
  prefix: Инсп. ВП
  paygrade: O4

# Fax responder
- type: rank
  id: RMCRankProvostCommunicationsOfficer
  name: Офицер связи
  prefix: Офиц. связи
  paygrade: O2

# Любой игрок с низким пониманием закона, с доп. помощью
- type: rank
  id: RMCRankProvostAdvisor
  name: Сержант Майор
  prefix: Серж. Майор
  paygrade: E9E

# Любой игрок с определенной целью, возможно лидер группы
- type: rank
  id: RMCRankProvostProvostTeamLeader
  name: Мастер Сержант
  prefix: Маст. Серж.
  paygrade: E8

# Любой игрок с определенной целью, член группы
- type: rank
  id: RMCRankProvostProvostEnforcer
  name: Старший Сержант
  prefix: Ст. Серж.
  paygrade: E6
