using System.Globalization;
using System.Linq;
using Content.Shared._Stories.SCCVars;
using Content.Shared.Radio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;

namespace Content.Client.Options.UI.Tabs
{
    [GenerateTypedNameReferences]
    public sealed partial class TTSTab : Control
    {
        [Dependency] private readonly IConfigurationManager _cfg = default!;
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

        public TTSTab()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            Control.AddOptionCheckBox(SCCVars.TTSEnabledClient, TtsEnabledCheckBox);

            Control.AddOptionPercentSlider(
                SCCVars.TTSVolumeMaster,
                SliderVolumeMasterTTS);

            Control.AddOptionPercentSlider(
                SCCVars.TTSVolumeAnnounce,
                SliderVolumeAnnounce);

            Control.AddOptionPercentSlider(
                SCCVars.TTSVolumeMarines,
                SliderVolumeMarines);

            Control.AddOptionPercentSlider(
                SCCVars.TTSVolumeXenos,
                SliderVolumeXenos);

            Control.AddOptionPercentSlider(
                SCCVars.TTSVolumeOther,
                SliderVolumeOther);

            Control.AddOptionPercentSlider(
                SCCVars.TTSVolumeRadio,
                SliderVolumeRadio);

            var loc = IoCManager.Resolve<ILocalizationManager>();

            var channels = _prototypeManager.EnumeratePrototypes<RadioChannelPrototype>()
                .Where(c => c.ShowInTTSOptions)
                .GroupBy(c => c.TtsCategory ?? "stories-tts-category-radio-general")
                .OrderBy(g => Loc.GetString(g.Key));

            foreach (var group in channels)
            {
                var label = new Label
                {
                    Text = Loc.GetString(group.Key),
                    StyleClasses = { "LabelHeading" },
                    Margin = new Robust.Shared.Maths.Thickness(0, 10, 0, 5)
                };
                RadioVolumesContainer.AddChild(label);

                foreach (var channel in group.OrderBy(c => Loc.GetString(c.Name)))
                {
                    var slider = new OptionSlider { Title = Loc.GetString(channel.Name) };
                    slider.NameLabel.FontColorOverride = channel.Color;
                    RadioVolumesContainer.AddChild(slider);

                    Control.AddOption(new OptionRadioVolume(Control, _cfg, slider, channel.ID, loc));
                }
            }

            Control.Initialize();
        }

        private sealed class OptionRadioVolume : BaseOption
        {
            private readonly IConfigurationManager _cfg;
            private readonly OptionSlider _slider;
            private readonly string _channelId;
            private readonly ILocalizationManager _loc;

            public OptionRadioVolume(OptionsTabControlRow controller, IConfigurationManager cfg, OptionSlider slider, string channelId, ILocalizationManager loc) : base(controller)
            {
                _cfg = cfg;
                _slider = slider;
                _channelId = channelId;
                _loc = loc;

                slider.Slider.MinValue = 0;
                slider.Slider.MaxValue = 1;
                slider.Slider.OnValueChanged += _ =>
                {
                    ValueChanged();
                    UpdateLabelValue();
                };
            }

            private Dictionary<string, float> GetDict()
            {
                var str = _cfg.GetCVar(SCCVars.TTSRadioVolumes);
                var dict = new Dictionary<string, float>();
                if (string.IsNullOrWhiteSpace(str)) return dict;

                var pairs = str.Split(';');
                foreach (var pair in pairs)
                {
                    var kv = pair.Split('=');
                    if (kv.Length == 2 && float.TryParse(kv[1], CultureInfo.InvariantCulture, out var vol))
                    {
                        dict[kv[0]] = vol;
                    }
                }
                return dict;
            }

            private void SaveDict(Dictionary<string, float> dict)
            {
                var str = string.Join(";", dict.Select(kv => $"{kv.Key}={kv.Value.ToString(CultureInfo.InvariantCulture)}"));
                _cfg.SetCVar(SCCVars.TTSRadioVolumes, str);
            }

            public override void LoadValue()
            {
                var dict = GetDict();
                var val = dict.GetValueOrDefault(_channelId, 1.0f);
                _slider.Slider.Value = val;
                UpdateLabelValue();
            }

            public override void SaveValue()
            {
                var dict = GetDict();
                dict[_channelId] = _slider.Slider.Value;
                SaveDict(dict);
            }

            public override void ResetToDefault()
            {
                _slider.Slider.Value = 1.0f;
                UpdateLabelValue();
            }

            public override bool IsModified()
            {
                var dict = GetDict();
                var current = dict.GetValueOrDefault(_channelId, 1.0f);
                return !MathHelper.CloseToPercent(current, _slider.Slider.Value);
            }

            public override bool IsModifiedFromDefault()
            {
                return !MathHelper.CloseToPercent(1.0f, _slider.Slider.Value);
            }

            private void UpdateLabelValue()
            {
                _slider.ValueLabel.Text = _loc.GetString("ui-options-value-percent", ("value", _slider.Slider.Value));
            }
        }
    }
}
