# - type: ttsSanitizeConfig
#   id: Default
#   allowedCharsRegex: "[^a-zA-Zа-яА-ЯёЁ0-9,\\-+?!. ]"
#   phoneticAlphabet:
#     A: "Эй "
#     B: "Би "
#     C: "Си "
#     D: "Ди "
#     E: "И "
#     F: "Эф "
#     G: "Джи "
#     H: "Эйч "
#     I: "Ай "
#     J: "Джей "
#     K: "Кей "
#     L: "Эл "
#     M: "Эм "
#     N: "Эн "
#     O: "О "
#     P: "Пи "
#     Q: "Кью "
#     R: "Ар "
#     S: "Эс "
#     T: "Ти "
#     U: "Ю "
#     V: "Ви "
#     W: "Дабл-ю "
#     X: "Икс "
#     Y: "Уай "
#     Z: "Зет "
#     А: "А "
#     Б: "Бэ "
#     Г: "Гэ "
#     Д: "Дэ "
#     Е: "Е "
#     Ё: "Ё "
#     Ж: "Жэ "
#     З: "Зэ "
#     И: "И "
#     Й: "И краткое "
#     К: "Ка "
#     Л: "Эль "
#     М: "Эм "
#     Н: "Эн "
#     О: "О "
#     П: "Пэ "
#     Р: "Эр "
#     С: "Эс "
#     Т: "Тэ "
#     У: "У "
#     Ф: "Эф "
#     Х: "Ха "
#     Ц: "Цэ "
#     Ч: "Че "
#     Ш: "Ша "
#     Щ: "Ща "
#     Ъ: "Твердый знак "
#     Ы: "Ы "
#     Ь: "Мягкий знак "
#     Э: "Э "
#     Ю: "Ю "
#     Я: "Я "
#   reverseTranslit:
#     a: "а"
#     b: "б"
#     v: "в"
#     g: "г"
#     d: "д"
#     e: "е"
#     je: "ё"
#     zh: "ж"
#     z: "з"
#     i: "и"
#     y: "й"
#     k: "к"
#     l: "л"
#     m: "м"
#     n: "н"
#     o: "о"
#     p: "п"
#     r: "р"
#     s: "с"
#     t: "т"
#     u: "у"
#     f: "ф"
#     h: "х"
#     c: "ц"
#     x: "кс"
#     ch: "ч"
#     sh: "ш"
#     jsh: "щ"
#     hh: "ъ"
#     ih: "ы"
#     jh: "ь"
#     eh: "э"
#     ju: "ю"
#     ja: "я"
