using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stories.Ordnance.Triggers;

[GenerateTypedNameReferences]
public sealed partial class OrdnanceTimerWindow : DefaultWindow
{
    public OrdnanceTimerWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
