using System.Linq;
using Content.Shared._Stories.Hunter.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Stories.Hunter.Profiles.UI;

[GenerateTypedNameReferences]
public sealed partial class SpritePicker : ScrollContainer
{
    private readonly List<SpritePickerButton> _buttons = new();

    public SpritePicker()
    {
        RobustXamlLoader.Load(this);
    }

    public event Action<EntProtoId>? OnSelectionChanged;

    public void Populate(IEnumerable<HunterGearPrototype> gearList, bool isSponsor)
    {
        Container.DisposeAllChildren();
        _buttons.Clear();

        var sortedGear = gearList.OrderBy(p => p.Name).ToList();

        foreach (var gear in sortedGear)
        {
            var isUnlocked = !gear.SponsorOnly || isSponsor;
            
            var button = new SpritePickerButton(gear.EntityProto, gear.SponsorOnly, isUnlocked);

            button.OnPressed += _ =>
            {
                if (button.IsLocked) 
                    return;

                OnSelectionChanged?.Invoke(gear.EntityProto);
                SetSelected(gear.EntityProto);
            };

            Container.AddChild(button);
            _buttons.Add(button);
        }
    }

    public void AddCustomButton(string id, string name, bool isSponsor, bool isUnlocked)
    {
        var button = new SpritePickerButton(id, isSponsor, isUnlocked);
        button.ToolTip = name;
        
        button.OnPressed += _ =>
        {
            if (button.IsLocked) return;
            OnSelectionChanged?.Invoke(id);
            SetSelected(id);
        };
        
        Container.AddChild(button);
        button.SetPositionFirst();
        _buttons.Add(button);
    }

    public void SetSelected(EntProtoId prototype)
    {
        foreach (var button in _buttons)
        {
            var shouldBePressed = button.Prototype == prototype;

            if (button.Pressed != shouldBePressed)
                button.Pressed = shouldBePressed;

            button.UpdateHighlight();
        }
    }
}
