using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;

namespace Content.Client._Stories.Hunter.Profiles.UI;

[GenerateTypedNameReferences]
public sealed partial class SpritePickerButton : ContainerButton
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private EntityUid? _dummy;
    public EntProtoId Prototype { get; }
    public bool IsSponsorItem { get; }
    public bool IsLocked { get; }

    public SpritePickerButton(EntProtoId prototype, bool isSponsorItem, bool isUnlocked)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Prototype = prototype;
        IsSponsorItem = isSponsorItem;
        IsLocked = isSponsorItem && !isUnlocked;

        ToggleMode = true;

        if (prototype == "Nothing")
        {
            ToolTip = Loc.GetString("st-hunter-gear-none");
            NoneTexture.Visible = true;
        }
        else if (_prototypeManager.TryIndex(prototype, out var proto))
        {
            ToolTip = proto.Name;
            _dummy = _entityManager.SpawnEntity(prototype, MapCoordinates.Nullspace);
            SpriteView.SetEntity(_dummy);
        }

        if (IsSponsorItem)
        {
            SponsorHighlight.Visible = true;
            ToolTip += "\n" + Loc.GetString("st-hunter-gear-sponsor-only");
        }

        if (IsLocked)
        {
            LockOverlay.Visible = true;
            MouseFilter = MouseFilterMode.Stop;
            ToolTip += "\n" + Loc.GetString("st-hunter-gear-locked");
        }

        OnToggled += args =>
        {
            if (IsLocked)
            {
                Pressed = false;
                return;
            }
            UpdateHighlight();
        };

        UpdateHighlight();
    }

    public void UpdateHighlight()
    {
        if (Highlight != null)
            Highlight.Visible = Pressed;
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing && _dummy.HasValue)
        {
            _entityManager.DeleteEntity(_dummy.Value);
            _dummy = null;
        }

        base.Dispose(disposing);
    }
}
